### ISSUE TITLE
[NOT RAN LOCALLY]Bot leaves Discord Server immediatly.

### ISSUE THREAD

**Issue by xproot** [Forcellrus/Discord-Auto-Publisher#12]
As the title says, I'm using the one hosted by you. It just leaves instantly on join, no more, no less. Help.

**Comment by weirdbandkid** [comment]
It means your server has been blacklisted. It has happened to me too. But I am fortunate enough to have my own server to host the bot. I can let you use the [bot](https://discord.com/api/oauth2/authorize?client_id=866380518253527070&permissions=10240&scope=bot) if you want.

**Comment by Forcellrus** [comment]
> As the title says, I'm using the one hosted by you. It just leaves instantly on join, no more, no less. Help.

As @weirdbandkid mentioned, your server has been most likely blacklisted due to spam. Please message me on Discord Forcellrus#5555 with more details.

**Comment by xproot** [comment]
Ah, I'm guessing I was going over the 10 message limit a lot, I'll host my own later.

**Comment by Forcellrus** [comment]
> Ah, I'm guessing I was going over the 10 message limit a lot, I'll host my own later.

Most likely, though the bot allows for some flexibility and it will very rarely blacklist if there were less than 40 messages per hour per channel. You won't really benefit much with a self-hosted bot as your posting bot/schedule is unoptimized, not quite what Discord's announcement channels were designed for. In other words, if you cross the 40 messages mark often, less than 1/4 of your messages will actually get published. You might want to revise your posting bot or optimize the posting schedule if it's done manually by your users.
