### ISSUE TITLE
Bot doesn't crosspost all messages.

### ISSUE THREAD

**Issue by MichalD96** [Forcellrus/Discord-Auto-Publisher#13]
I have a discord server with 20 announcements channels. I post there game updates by sending webhooks from my VPS server. 1 channel is updated once an hour, 14 channels is updated once a day, and last 5 once a week or once a month.
I use Auto Publisher bot for this for around a year and it is first time i have any issues. Since 3 days bot randomly crosspost some messages and some not. Bot has granted all required permissions (Read Messages, Send Messages, Manage Messages, Read Message History) on AutoPublisher role, and also on every announcement channel.
I am sure i have not exceeded any limit (i know Discord limit is 10 (messages/hour)/channel) when i post max 1 message per hour on only one channel.

Discord server ID: 755631770480803931

**Comment by Forcellrus** [comment]
Greetings, multiple people reported the same issue and it's also happening on my server. I'm already working on fixing this problem.

**Comment by FlareFlo** [comment]
Without adding unnecessary input,  this issue appears to be unrelated to

- The channel the message is posted in
- The type of message (equal content and near-simultaneous messages on different channels are not broadcasted)

**Comment by Forcellrus** [comment]
I deployed the fixed (v2) version of the bot, so far I don't issues with random crosspost misses anymore. Let me know if the issues persist!
