### ISSUE TITLE
The bot auto leaves when i tries to add it

### ISSUE THREAD

**Issue by biast12** [Forcellrus/Discord-Auto-Publisher#24]
![image](https://user-images.githubusercontent.com/53872542/202191226-cf0f0e73-44e0-43e3-bb5d-6e3b68e2ed15.png)

**Comment by Forcellrus** [comment]
It appears your server has been blacklisted, as per [readme](https://github.com/Forcellrus/Discord-Auto-Publisher/blob/main/README.md). Please contact me on Discord for appeals.

**Comment by biast12** [comment]
sorry missed that, send you a friend request so i can explain a little about my server
