### ISSUE TITLE
The bot doesn't publish anything

### ISSUE THREAD

**Issue by Xwilarg** [Forcellrus/Discord-Auto-Publisher#5]
Hi,

I invited your bot to my server where I have one annoucement channel but the bot doesn't do anything when there is a new message in it.
I only gave him the "Manage Messages" permission on this specific channel, I don't know if that can affect his behavior?

**Comment by Forcellrus** [comment]
Greetings! If you are still experiencing this issue, please poke me on Discord `Forcellrus#5555`.

**Comment by Xwilarg** [comment]
Well turned out I just didn't read the README properly (I had a channel with just "Manage Messages" and not "Send Messages"), I'm closing the issue, thanks for the help!
