### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by PuneetGopinath** [Forcellrus/Discord-Auto-Publisher#7]
I have a question, but if you feel to not share it, you can close this issue
Where did you host your bot, in Heroku or somewhere else?
And are you using a free plan on that platform?

**Comment by Forcellrus** [comment]
Hey, the bot is hosted on a paid VPS based in Germany. Are you experiencing issues with the bot that would indicate poor server performance due to free plans or is your question out of curiosity?

**Comment by PuneetGopinath** [comment]
> Hey, the bot is hosted on a paid VPS based in Germany. Are you experiencing issues with the bot that would indicate poor server performance due to free plans or is your question out of curiosity?

No issues, works cool, I am just asking out of curiosity.

**Comment by PuneetGopinath** [comment]
I asked because maybe one day, I too will host.
